### ISSUE TITLE
Validate param values not being strings unnecessarily

### ISSUE THREAD

**Issue by chriskelly** [chriskelly/LifeFInances#94]
Many param values are in string format because tkinter fields are interpreted as strings. Since we're moving away from tkinter, we should try to convert all param.json values into their regular forms ("False" -> false, "1.03" -> 1.03) for simplicities sake. Validation would require running simulator.py and genetic.py

**Comment by 10CDizzle** [comment]
I'll write a helper function. perhaps we can stow it it __init__.py so it runs automatically whenever something like constants.py is imported
